# Run tests for all supported python versions
name: tests

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Run tests with pytest
      run: |
        poetry run coverage run -m pytest
    - name: Upload coverage statistics to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: poetry run coveralls
